# Generated by Django 4.2.7 on 2023-12-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_train_destination_train_name_train_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
