# Generated by Django 4.2.7 on 2023-12-26 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_train_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='seats',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
