# Generated by Django 4.2.7 on 2023-12-26 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_train_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='destination',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='train',
            name='start',
            field=models.CharField(max_length=100),
        ),
    ]
