# Generated by Django 4.2.7 on 2023-12-26 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_alter_train_destination_alter_train_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='train',
            name='operating_days',
        ),
        migrations.AddField(
            model_name='train',
            name='operating_days',
            field=models.ManyToManyField(to='task.day'),
        ),
    ]
