# Generated by Django 4.2.7 on 2024-01-02 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_alter_wallet_user_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='booked_seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='task.section'),
        ),
    ]
