# Generated by Django 4.2.7 on 2023-12-30 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_day_remove_train_operating_days_train_operating_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('General', 'General'), ('Sleeper', 'Sleeper'), ('3A', '3A'), ('2A', '2A'), ('First Class', 'First Class')], max_length=11)),
            ],
        ),
        migrations.RemoveField(
            model_name='train',
            name='price',
        ),
        migrations.RemoveField(
            model_name='train',
            name='seats',
        ),
        migrations.AddField(
            model_name='train',
            name='time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.CreateModel(
            name='sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('number', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('section', models.ManyToManyField(to='task.choices')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.train')),
            ],
        ),
    ]
