# Generated by Django 4.2.7 on 2023-12-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_choices_remove_train_price_remove_train_seats_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sections',
            name='section',
        ),
        migrations.RemoveField(
            model_name='sections',
            name='name',
        ),
        migrations.AddField(
            model_name='sections',
            name='name',
            field=models.ManyToManyField(to='task.choices'),
        ),
    ]
