# Generated by Django 4.2.7 on 2024-01-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_passenger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='booking',
        ),
        migrations.AddField(
            model_name='booking',
            name='passengers',
            field=models.ManyToManyField(to='task.passenger'),
        ),
    ]
