# Generated by Django 4.2.7 on 2023-12-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_remove_sections_section_remove_sections_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choices',
            name='name',
            field=models.CharField(choices=[('General', 'General'), ('Sleeper', 'Sleeper'), ('3A', '3A'), ('2A', '2A'), ('First Class', 'First Class')], max_length=12),
        ),
        migrations.AlterField(
            model_name='sections',
            name='name',
            field=models.ManyToManyField(to='task.day'),
        ),
    ]
