# Generated by Django 4.2.7 on 2023-12-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_alter_choices_name_alter_sections_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sections',
            name='name',
            field=models.ManyToManyField(to='task.choices'),
        ),
    ]
