# Generated by Django 4.2.7 on 2024-01-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_remove_passenger_booking_booking_passengers'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='seat_num',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
