# Generated by Django 4.2.7 on 2023-12-31 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_alter_sections_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
