# Generated by Django 4.2.7 on 2024-01-06 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_alter_passenger_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='gender',
        ),
    ]
