# Generated by Django 4.2.7 on 2024-01-06 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0013_remove_passenger_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='passengers',
        ),
        migrations.DeleteModel(
            name='Passenger',
        ),
    ]
