# Generated by Django 4.2.7 on 2024-01-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0014_remove_booking_passengers_delete_passenger'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='passengers',
            field=models.ManyToManyField(to='task.passenger'),
        ),
    ]
