# Generated by Django 4.2.7 on 2024-01-18 13:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0016_alter_booking_num_seats_alter_passenger_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
